python DANN_5.py -p1 'Figures_M_7/T1/D_Loss.png' -p2 'Figures_M_7/T1/C_loss.png' -p3 'Figures_M_7/T1/Total_loss.png' -p4 'Figures_M_7/T1/DANN_CM.png' > Figures_M_7/T1/Model_Report.txt
python DANN_5.py -p1 'Figures_M_7/T2/D_Loss.png' -p2 'Figures_M_7/T2/C_loss.png' -p3 'Figures_M_7/T2/Total_loss.png' -p4 'Figures_M_7/T2/DANN_CM.png' > Figures_M_7/T2/Model_Report.txt
python DANN_5.py -p1 'Figures_M_7/T3/D_Loss.png' -p2 'Figures_M_7/T3/C_loss.png' -p3 'Figures_M_7/T3/Total_loss.png' -p4 'Figures_M_7/T3/DANN_CM.png' > Figures_M_7/T3/Model_Report.txt
python DANN_5.py -p1 'Figures_M_7/T4/D_Loss.png' -p2 'Figures_M_7/T4/C_loss.png' -p3 'Figures_M_7/T4/Total_loss.png' -p4 'Figures_M_7/T4/DANN_CM.png' > Figures_M_7/T4/Model_Report.txt
python DANN_5.py -p1 'Figures_M_7/T5/D_Loss.png' -p2 'Figures_M_7/T5/C_loss.png' -p3 'Figures_M_7/T5/Total_loss.png' -p4 'Figures_M_7/T5/DANN_CM.png' > Figures_M_7/T5/Model_Report.txt
python DANN_5.py -p1 'Figures_M_7/T6/D_Loss.png' -p2 'Figures_M_7/T6/C_loss.png' -p3 'Figures_M_7/T6/Total_loss.png' -p4 'Figures_M_7/T6/DANN_CM.png' > Figures_M_7/T6/Model_Report.txt
python DANN_5.py -p1 'Figures_M_7/T7/D_Loss.png' -p2 'Figures_M_7/T7/C_loss.png' -p3 'Figures_M_7/T7/Total_loss.png' -p4 'Figures_M_7/T7/DANN_CM.png' > Figures_M_7/T7/Model_Report.txt
python DANN_5.py -p1 'Figures_M_7/T8/D_Loss.png' -p2 'Figures_M_7/T8/C_loss.png' -p3 'Figures_M_7/T8/Total_loss.png' -p4 'Figures_M_7/T8/DANN_CM.png' > Figures_M_7/T8/Model_Report.txt
python DANN_5.py -p1 'Figures_M_7/T9/D_Loss.png' -p2 'Figures_M_7/T9/C_loss.png' -p3 'Figures_M_7/T9/Total_loss.png' -p4 'Figures_M_7/T9/DANN_CM.png' > Figures_M_7/T9/Model_Report.txt
python DANN_5.py -p1 'Figures_M_7/T10/D_Loss.png' -p2 'Figures_M_7/T10/C_loss.png' -p3 'Figures_M_7/T10/Total_loss.png' -p4 'Figures_M_7/T10/DANN_CM.png' > Figures_M_7/T10/Model_Report.txt
